---
- name: destroy Grafana
  hosts: hosts
  become: yes
  
  tasks:
  - name: delete apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      id: B53AE77BADB630A683046005963FA27710458545
      state: absent
  - name: remove Grafana repo to source.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: absent
  - name: Ensure Grafana is started and enabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: no
      state: stopped
  - name: remove Grafana
    ansible.builtin.apt:
      name: grafana
      state: absent
      
      
      