---
- name: Install Jenkins
  hosts: localhost
  remote_user: lateefat
  become: yes
  
  tasks:
  - name: download apt key for jenkins
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present
  - name: Add Jenkins repo to source.list
    ansible.builtin.apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      filename: jenkins
      state: present
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
  - name: Install fontconfig
    shell: apt install fontconfig -y 
  - name: Install java
    shell: apt install fontconfig openjdk-17-jre -y 
  - name: Update apt cache and install Jenkins
    apt:
      name: jenkins
      update_cache: yes
  - name: Ensure Jenkins is started and enabled
    ansible.builtin.systemd:
      name: jenkins
      enabled: yes
      state: started